name: Auto Merge Branch CI

on:
  push:
    branches-ignore:
      - main # main을 제외한 branch에서만 push 감지

env:
  JWT_ISSUER: min429
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 병합을 위해 전체 history 가져옴

    - name: Set up Git
      run: |
        git config --global user.name 'min429'
        git config --global user.email 'lsm990429@gmail.com'

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306
        container port: 3306
        character set server: 'utf8mb4'
        collation server: 'utf8mb4_general_ci'
        mysql version: '9.0'
        mysql database: 'tour-platform'
        mysql user: 'root'
        mysql password: '1234'

    - name: Set up MongoDB
      uses: getong/mongo-action@v1.1
      with:
        mongo version: '7.0'
        host port: 27017
        mongo username: 'root'
        mongo password: '1234'
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Build with Gradle Wrapper
      run: ./gradlew build -s

    - name: Merge dev into main
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      run: |
        git checkout main
        git pull origin main
        git merge --no-ff dev
        git push origin main
