name: Java CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JWT_ISSUER: 'DND-11-1'
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Call common steps
        uses: ./.github/workflows/common-steps.yml

      - name: Build with Gradle Wrapper
        run: ./gradlew build -d

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Call common steps
        uses: ./.github/workflows/common-steps.yml

      - name: Test with Gradle Wrapper
        run: ./gradlew test -d

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v3
