name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          host port: 3306
          container port: 3306
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_general_ci'
          mysql version: '9.0'
          mysql database: 'tour-platform'
          mysql user: 'root'
          mysql password: '1234'

      - name: Set up MongoDB
        uses: getong/mongo-action@v1.1
        with:
          mongo version: '7.0'
          host port: 27017
          mongo username: 'root'
          mongo password: '1234'
          
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: test with Gradle Wrapper
        run: ./gradlew test -s
